name: Deploy Bot to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    environment: production  # Specify that this deployment is for the 'production' environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out your repository to the runner

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # This sets up the SSH key for authentication
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Make sure this is the correct secret name

    - name: Debug EC2 IP Address  # Optional step to debug EC2 IP
      run: echo "EC2 IP Address: ${{ secrets.EC2_IP_ADDRESS }}"

    - name: Connect to EC2 and Deploy Bot
      run: |
        echo "Starting deployment..."

        # Connect to EC2 instance via SSH
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
          echo "Connected to EC2"

          # Navigate to the bot directory
          cd ~/makima-bot
          echo "Pulling latest code from GitHub..."
          git pull origin main  # Pull the latest code from the repository

          # Activate the virtual environment
          echo "Activating virtual environment..."
          source venv/bin/activate

          # Install any dependencies
          echo "Installing dependencies..."
          pip install -r requirements.txt

          # Restart the bot using PM2
          echo "Restarting bot using PM2..."
          pm2 restart main.py --interpreter python3

          echo "Deployment completed."
        EOF
